[project]
name = "nerfstudio"
version = "0.1.0"
description = "Add a short description here"
authors = ["Zicklag <zicklag@katharostech.com>"]
channels = ["pytorch", "nvidia", "nvidia", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pip = ">=24.0,<25"
torchvision = ">=0.17.1,<0.18"
pytorch = ">=2.2.1,<2.3"
pytorch-cuda = ">=12.1,<13"
cuda-toolkit = ">=12.1.0,<12.2"
ninja = ">=1.11.1,<1.12"

